const orgs = [
  { acr: "AGO", name: "Attorney General's Office" },
  { acr: "APA", name: "Asset Protection Agency" },
  { acr: "BIS", name: "Department for Business, Innovation and Skills" },
  {
    acr: "BEIS",
    name: "Department for Business, Energy and Industrial Strategy",
  },
  { acr: "CO", name: "Cabinet Office" },
  {
    acr: "CxD",
    name: "Chancellor's Departments (APA, DMO, GAD, HMRC, HMT, NS&I, OBR)",
  },
  { acr: "DCLG", name: "Department for Communities and Local Government" },
  { acr: "DCMS", name: "Department for Digital, Culture, Media and Sport" },
  { acr: "DECC", name: "Department of Energy and Climate Change" },
  { acr: "Defra", name: "Department for Environment, Food and Rural Affairs" },
  { acr: "DE&S", name: "Defence Equipment and Support (part of MoD)" },
  { acr: "DExEU", name: "Department for Exiting the European Union" },
  { acr: "DfE", name: "Department for Education" },
  { acr: "DfID", name: "Department for International Development" },
  { acr: "DfT", name: "Department for Transport" },
  { acr: "DH", name: "Department of Health" },
  { acr: "DHSC", name: "Department of Health and Social Care" },
  { acr: "DMO", name: "Debt Management Office" },
  { acr: "DPM", name: "Deputy Prime Minister" },
  { acr: "DVLA", name: "Driver and Vehicle Licensing Agency (part of DfT)" },
  { acr: "DWP", name: "Department for Work and Pensions" },
  { acr: "ERG", name: "Efficiency and Reform Group (part of CO)" },
  { acr: "FCO", name: "Foreign and Commonwealth Office" },
  { acr: "GAD", name: "Government Actuary's Department" },
  { acr: "GDS", name: "Government Digital Service" },
  {
    acr: "HCS",
    name: "Home Civil Service (all civil servants in UK, Scottish and Welsh governments)",
  },
  { acr: "HMRC", name: "Her Majesty's Revenue and Customs" },
  { acr: "HMT", name: "Her Majesty's Treasury" },
  { acr: "HO", name: "Home Office" },
  { acr: "HofC", name: "House of Commons" },
  { acr: "HofL", name: "House of Lords" },
  { acr: "IPA", name: "Infrastructure and Projects Authority" },
  {
    acr: "Law",
    name: "Law officers (AGO, Office of the Advocate General for Scotland)",
  },
  {
    acr: "MHCLG",
    name: "MInistry of Housing, Communities and Local Government",
  },
  { acr: "MoD", name: "Ministry of Defence" },
  { acr: "MoJ", name: "Ministry for Justice" },
  { acr: "MPA", name: "Major Projects Authority (part of CO)" },
  { acr: "NAO", name: "National Audit Office" },
  { acr: "NHS", name: "National Health Service" },
  { acr: "NICS", name: "Northern Ireland Civil Service" },
  { acr: "NIO", name: "Northern Ireland Office" },
  { acr: "NS&I", name: "National Savings and Investments" },
  { acr: "OBR", name: "Office for Budget Responsibility" },
  { acr: "ONS", name: "Office for National Statistics" },
  { acr: "PM", name: "Prime Minister" },
  { acr: "Scot", name: "Scotland Office" },
  { acr: "SG", name: "Scottish Government" },
  { acr: "Wal", name: "Wales Office" },
  { acr: "WG", name: "Welsh Government" },
];
